export const handleTypes = {
  SOURCE: 'SOURCE',
  WINDOW_RESIZE: 'WINDOW_RESIZE',
  SCROLL: 'SCROLL_POSITION',
  RECENTS: 'RECENTS',
  USER: 'USER',
  BOOKMARKS: 'BOOKMARKS',
  LOADING: "LOADING",
  LAYOUT: "LAYOUT",
  DEL_RECENTS: 'DEL_RECENTS',
  DEL_BOOKMARKS: 'DEL_BOOKMARKS',
  FILTER_CHAPTER: 'FILTER_CHAPTER'
}